import React, { useState } from 'react';
import { Outlet, useLocation } from 'react-router-dom';
import AdminSidebar from '../components/admin/AdminSidebar';
import AdminHeader from '../components/admin/AdminHeader';

const AdminLayout = () => {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const location = useLocation();

  const getPageInfo = () => {
    switch (location.pathname) {
      case '/admin/dashboard':
        return { title: 'System Overview & Platform Health', subtitle: 'Global user statistics, aggregate solar capacity, and environmental metrics' };
      case '/admin/users':
        return { title: 'User Management Directory', subtitle: 'Browse, filter, and inspect registered consumers across all 4 categories' };
      case '/admin/reports':
        return { title: 'Generated Audit Reports', subtitle: 'View, verify, and inspect solar assessments generated by users' };
      case '/admin/analytics':
        return { title: 'Platform Yields & Analytics', subtitle: 'Category breakdowns, capacity distributions, and monthly trends' };
      case '/admin/settings':
        return { title: 'Dynamic System Parameters', subtitle: 'Adjust base equipment costs, tariffs, subsidy caps, and solar resources' };
      default:
        return { title: 'Admin Console', subtitle: 'SolarSense AI Platform Administration' };
    }
  };

  const info = getPageInfo();

  return (
    <div className="min-h-screen bg-light-bg text-light-text flex antialiased">
      <AdminSidebar mobileOpen={mobileMenuOpen} setMobileOpen={setMobileMenuOpen} />
      
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden bg-light-bg">
        <AdminHeader
          title={info.title}
          subtitle={info.subtitle}
          onOpenMobileMenu={() => setMobileMenuOpen(true)}
        />

        <main className="flex-1 overflow-y-auto p-4 sm:p-6 bg-light-bg">
          <Outlet />
        </main>
      </div>
    </div>
  );
};

export default AdminLayout;
