require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const SolarCompany = require('../models/SolarCompany');
const CompanyPriceSnapshot = require('../models/CompanyPriceSnapshot');

const companiesData = [
  {
    name: 'Tata Power Solar',
    slug: 'tata-power-solar',
    type: 'Both',
    officialWebsite: 'https://www.tatapowersolar.com',
    quoteUrl: 'https://www.tatapowersolar.com/rooftops/residential/',
    headquarters: 'Mumbai, Maharashtra',
    establishedYear: 1989,
    products: ['Residential Rooftop Solar', 'C&I Microgrids', 'Mono PERC Modules', 'Inverters & Storage'],
    panelTechnology: ['Mono PERC', 'TOPCon', 'Bifacial'],
    cellTechnology: 'N-Type TOPCon & Mono PERC',
    efficiencyPercent: 22.1,
    annualDegradation: '0.45% / yr linear',
    advantages: [
      '35+ years engineering heritage backed by Tata Group trust and highest bankability in India.',
      'Turnkey residential EPC with direct DISCOM net-metering liaison and PM Surya Ghar handling.',
      'Largest PAN-India authorized service network with guaranteed 48-hr ticket resolution.',
      '25-year linear performance warranty with guaranteed low first-year degradation (< 2%).'
    ],
    disadvantages: [
      'Turnkey price (₹58k–₹65k/kW) is at a premium compared to local unorganized installers.',
      'Site inspection and installation lead times can be longer in remote or rural districts.',
      'Strict roof structural eligibility criteria; may decline installation on aged roofs.'
    ],
    productWarrantyYears: 12,
    performanceWarrantyYears: 25,
    installationAvailability: 'Nationwide',
    statesServed: ['All India'],
    tier: 'Tier-1',
    pricePerKWMin: 58000,
    pricePerKWMax: 65000,
    priceDisplay: '₹58,000 – ₹65,000 / kW',
    priceType: 'turnkey',
    inverterPartners: ['Tata Power Solar Inverters', 'Sungrow', 'Enphase'],
    amcAvailable: true,
    financingAvailable: true,
    subsidySupport: true,
    netMeteringSupport: true,
    evaluation: {
      overallScore: 9.3,
      priceValue: 8.5,
      productQuality: 9.6,
      warrantyScore: 9.3,
      installationScore: 9.4,
      serviceScore: 9.3,
      availabilityScore: 9.6,
      technologyScore: 9.2,
      assessmentDisclaimer: 'Tata Group pedigree with the largest nationwide engineering, procurement, and construction network in India.',
    },
    bestFor: 'Best Overall & Long-Term Reliability',
    source: 'Official Tata Power Solar Annual Technical Brief 2025-2026',
    lastVerified: 'March 2026',
    featured: true,
  },
  {
    name: 'Waaree Energies',
    slug: 'waaree-energies',
    type: 'Both',
    officialWebsite: 'https://www.waaree.com',
    quoteUrl: 'https://www.waaree.com/residential-solar',
    headquarters: 'Mumbai, Maharashtra',
    establishedYear: 1989,
    products: ['Elite Mono PERC', 'Arka Bifacial Glass-Glass', 'Turnkey Rooftop EPC', 'Solar Pumps'],
    panelTechnology: ['TOPCon', 'N-Type', 'Mono PERC', 'Bifacial'],
    cellTechnology: 'N-Type TOPCon Dual-Glass',
    efficiencyPercent: 22.6,
    annualDegradation: '0.40% / yr linear',
    advantages: [
      'India’s largest module manufacturing capacity (12+ GW) ensuring immediate stock availability.',
      'Industry-leading 30-year linear performance warranty on bifacial dual-glass series.',
      'Over 500+ franchise stores and localized distributor warehouses in almost every district.',
      'Full PM Surya Ghar Domestic Content Requirement (DCR) compliance and ALMM listed.'
    ],
    disadvantages: [
      'Residential rooftop EPC execution depends largely on local franchise partner craftsmanship.',
      'Customer support resolution can encounter delays when dealing with franchise disputes.',
      'Turnkey price variations across different state franchise partners.'
    ],
    productWarrantyYears: 12,
    performanceWarrantyYears: 30,
    installationAvailability: 'Nationwide',
    statesServed: ['All India'],
    tier: 'Tier-1',
    pricePerKWMin: 52000,
    pricePerKWMax: 58000,
    priceDisplay: '₹52,000 – ₹58,000 / kW',
    priceType: 'turnkey',
    inverterPartners: ['Waaree Inverters', 'Growatt', 'Sofar'],
    amcAvailable: true,
    financingAvailable: true,
    subsidySupport: true,
    netMeteringSupport: true,
    evaluation: {
      overallScore: 9.1,
      priceValue: 9.4,
      productQuality: 9.1,
      warrantyScore: 9.5,
      installationScore: 8.9,
      serviceScore: 8.8,
      availabilityScore: 9.7,
      technologyScore: 9.3,
      assessmentDisclaimer: "India's largest solar module manufacturer with over 12 GW installed capacity and 500+ franchise stores.",
    },
    bestFor: 'Best Value per Watt & High Availability',
    source: 'Waaree Energies Official Product Specs & MNRE ALMM List',
    lastVerified: 'March 2026',
    featured: true,
  },
  {
    name: 'Adani Solar',
    slug: 'adani-solar',
    type: 'Manufacturer',
    officialWebsite: 'https://www.adanisolar.com',
    quoteUrl: 'https://www.adanisolar.com/contact-us',
    headquarters: 'Ahmedabad, Gujarat',
    establishedYear: 2015,
    products: ['Elan Bifacial Dual-Glass', 'Shine Mono PERC', 'TOPCon Modules'],
    panelTechnology: ['TOPCon', 'Mono PERC', 'Bifacial'],
    cellTechnology: 'N-Type TOPCon & Bifacial',
    efficiencyPercent: 22.8,
    annualDegradation: '0.40% / yr linear',
    advantages: [
      'Vertically integrated gigafactory in Mundra spanning ingots, wafers, cells, and modules.',
      'Peak module conversion efficiency reaching up to 22.8% with cutting-edge TOPCon cells.',
      'Heavy mechanical wind load tolerance (5400 Pa front / 2400 Pa rear) ideal for cyclones/coastal.',
      'Tier-1 BloombergNEF bankability preferred by commercial banks for large solar loans.'
    ],
    disadvantages: [
      'Primarily focused on utility-scale and large commercial developers; minimal direct retail residential EPC.',
      'Homeowners must purchase through 3rd-party regional EPC contractors rather than directly from Adani.',
      'Net-metering liaison and after-sales maintenance depend entirely on the chosen local contractor.'
    ],
    productWarrantyYears: 12,
    performanceWarrantyYears: 25,
    installationAvailability: 'Nationwide',
    statesServed: ['All India'],
    tier: 'Tier-1',
    pricePerKWMin: 50000,
    pricePerKWMax: 56000,
    priceDisplay: '₹50,000 – ₹56,000 / kW (Equipment-indicative)',
    priceType: 'market_indicative',
    inverterPartners: ['Certified EPC Channel Partners (Sungrow, Huawei, Solis)'],
    amcAvailable: false,
    financingAvailable: true,
    subsidySupport: true,
    netMeteringSupport: false,
    evaluation: {
      overallScore: 8.9,
      priceValue: 8.8,
      productQuality: 9.4,
      warrantyScore: 8.9,
      installationScore: 8.2,
      serviceScore: 8.3,
      availabilityScore: 9.2,
      technologyScore: 9.5,
      assessmentDisclaimer: 'Tier-1 vertically integrated cell and module manufacturer. Installation executed via certified regional EPC channel partners.',
    },
    bestFor: 'High-Efficiency Commercial & Industrial Rooftops',
    source: 'Adani Solar Mundra Technical Datasheet & Verified Market Surveys',
    lastVerified: 'March 2026',
    featured: false,
  },
  {
    name: 'Vikram Solar',
    slug: 'vikram-solar',
    type: 'Both',
    officialWebsite: 'https://www.vikramsolar.com',
    quoteUrl: 'https://www.vikramsolar.com/contact/',
    headquarters: 'Kolkata, West Bengal',
    establishedYear: 2006,
    products: ['Suryava TOPCon Series', 'Somera Half-Cut Mono PERC', 'Utility & Rooftop EPC'],
    panelTechnology: ['TOPCon', 'Bifacial', 'Mono PERC'],
    cellTechnology: 'TOPCon & Half-Cut Multi-Busbar',
    efficiencyPercent: 22.3,
    annualDegradation: '0.45% / yr linear',
    advantages: [
      'Global Tier-1 track record with active installations across 32+ countries and stringent quality benchmarks.',
      'Low temperature coefficient (-0.30%/°C), generating superior yield in extreme Indian summers.',
      '27-year linear performance warranty with anti-PID (Potential Induced Degradation) cells.',
      'Extensive experience executing mission-critical government, airport, and military installations.'
    ],
    disadvantages: [
      'Higher pricing for the flagship Suryava TOPCon modules compared to standard Indian brands.',
      'Direct residential presence is smaller than Tata Power or Loom Solar; mainly commercial focus.',
      'Turnkey rooftop services usually require minimum 5 kW to 10 kW system capacities.'
    ],
    productWarrantyYears: 12,
    performanceWarrantyYears: 27,
    installationAvailability: 'Nationwide',
    statesServed: ['All India'],
    tier: 'Tier-1',
    pricePerKWMin: 53000,
    pricePerKWMax: 59000,
    priceDisplay: '₹53,000 – ₹59,000 / kW',
    priceType: 'turnkey',
    inverterPartners: ['Sungrow', 'GoodWe', 'Delta'],
    amcAvailable: true,
    financingAvailable: true,
    subsidySupport: true,
    netMeteringSupport: true,
    evaluation: {
      overallScore: 8.8,
      priceValue: 8.8,
      productQuality: 9.1,
      warrantyScore: 9.0,
      installationScore: 8.6,
      serviceScore: 8.6,
      availabilityScore: 8.9,
      technologyScore: 9.0,
      assessmentDisclaimer: 'Pioneer Indian manufacturer with active installations in 32+ countries and high mechanical load certifications.',
    },
    bestFor: 'Extreme Weather Durability & High Temperature Tolerance',
    source: 'Vikram Solar Official Technical Portfolio',
    lastVerified: 'March 2026',
    featured: false,
  },
  {
    name: 'Loom Solar',
    slug: 'loom-solar',
    type: 'Both',
    officialWebsite: 'https://www.loomsolar.com',
    quoteUrl: 'https://www.loomsolar.com/pages/contact-us',
    headquarters: 'Faridabad, Haryana',
    establishedYear: 2018,
    products: ['Shark Bi-Facial Solar Panels', 'Super High Efficiency Mono PERC', 'Lithium CAML Batteries'],
    panelTechnology: ['Bifacial', 'Mono PERC'],
    cellTechnology: 'Shark Bifacial 16-Busbar',
    efficiencyPercent: 22.0,
    annualDegradation: '0.50% / yr linear',
    advantages: [
      'Pioneer in consumer-first online ordering with doorstep delivery to 500+ Indian pin codes.',
      'Shark Bifacial panels produce up to 25% extra power from reflected light—ideal for small urban roofs.',
      'Transparent online pricing, plug-and-play kits, and integrated lithium storage options.',
      'Fast delivery timelines (3 to 7 days) for residential panels across metro cities.'
    ],
    disadvantages: [
      'Priced higher per watt than conventional monofacial panels.',
      'Relies on network of local freelance technicians for physical installation in Tier-2/3 towns.',
      'Less oriented toward multi-megawatt industrial solar farms.'
    ],
    productWarrantyYears: 10,
    performanceWarrantyYears: 25,
    installationAvailability: 'Nationwide',
    statesServed: ['All India'],
    tier: 'Premium',
    pricePerKWMin: 54000,
    pricePerKWMax: 62000,
    priceDisplay: '₹54,000 – ₹62,000 / kW',
    priceType: 'turnkey',
    inverterPartners: ['Loom Solar Inverters', 'Microtek', 'Luminous'],
    amcAvailable: true,
    financingAvailable: true,
    subsidySupport: true,
    netMeteringSupport: true,
    evaluation: {
      overallScore: 8.7,
      priceValue: 8.4,
      productQuality: 8.9,
      warrantyScore: 8.5,
      installationScore: 8.8,
      serviceScore: 8.7,
      availabilityScore: 9.4,
      technologyScore: 9.1,
      assessmentDisclaimer: 'Leading digital direct-to-consumer solar brand in India, famous for high-wattage Shark bifacial panels for compact residential roofs.',
    },
    bestFor: 'Compact Rooftops & High Wattage per Sq.Ft',
    source: 'Loom Solar Direct Portal Catalog',
    lastVerified: 'March 2026',
    featured: false,
  },
  {
    name: 'Premier Energies',
    slug: 'premier-energies',
    type: 'Both',
    officialWebsite: 'https://www.premierenergies.com',
    quoteUrl: 'https://www.premierenergies.com/contact-us',
    headquarters: 'Hyderabad, Telangana',
    establishedYear: 1995,
    products: ['DCR Mono PERC Modules', 'Bifacial Glass-Glass TOPCon', 'EPC Solutions'],
    panelTechnology: ['TOPCon', 'Mono PERC', 'Bifacial'],
    cellTechnology: 'N-Type TOPCon & DCR Cells',
    efficiencyPercent: 22.5,
    annualDegradation: '0.40% / yr linear',
    advantages: [
      'Ultra-modern robotic manufacturing facilities in Hyderabad with 30-year performance guarantee.',
      'Unmatched installer network and rapid engineering turnaround across South & Central India.',
      '100% compliant DCR (Domestic Content Requirement) modules ensuring maximum PM Surya Ghar subsidies.',
      'Publicly listed, highly capitalized company with solid long-term warranty backed reserves.'
    ],
    disadvantages: [
      'Brand recognition and direct EPC presence are relatively lower in North and North-East India.',
      'Does not manufacture proprietary inverters; packages systems with third-party inverter partners.'
    ],
    productWarrantyYears: 12,
    performanceWarrantyYears: 30,
    installationAvailability: 'Regional',
    statesServed: ['Telangana', 'Andhra Pradesh', 'Karnataka', 'Maharashtra', 'Tamil Nadu', 'All India'],
    tier: 'Tier-1',
    pricePerKWMin: 51000,
    pricePerKWMax: 57000,
    priceDisplay: '₹51,000 – ₹57,000 / kW',
    priceType: 'turnkey',
    inverterPartners: ['Havells', 'Sungrow', 'Growatt'],
    amcAvailable: true,
    financingAvailable: true,
    subsidySupport: true,
    netMeteringSupport: true,
    evaluation: {
      overallScore: 8.9,
      priceValue: 9.2,
      productQuality: 9.1,
      warrantyScore: 9.4,
      installationScore: 8.8,
      serviceScore: 8.9,
      availabilityScore: 8.8,
      technologyScore: 9.2,
      assessmentDisclaimer: 'State-of-the-art automated manufacturing facility in Hyderabad with extensive EPC delivery across South and Central India.',
    },
    bestFor: 'South & Central India Rooftops & Max Subsidies',
    source: 'Premier Energies Certified Catalog',
    lastVerified: 'March 2026',
    featured: false,
  },
  {
    name: 'Jakson Solar',
    slug: 'jakson-solar',
    type: 'Both',
    officialWebsite: 'https://www.jakson.com',
    quoteUrl: 'https://www.jakson.com/solar/rooftop-solar/',
    headquarters: 'Noida, Uttar Pradesh',
    establishedYear: 1947,
    products: ['Helia Series Mono PERC Modules', 'Hybrid Solar Inverters', 'Turnkey EPC'],
    panelTechnology: ['Mono PERC', 'Half-Cut Cell'],
    cellTechnology: 'Helia Mono PERC Half-Cut',
    efficiencyPercent: 21.6,
    annualDegradation: '0.55% / yr linear',
    advantages: [
      '75+ years engineering heritage in power backup and electrical infrastructure in India.',
      'Proprietary hybrid inverters and complete battery energy storage integration for power cut zones.',
      'Turnkey project execution with end-to-end electrical design and government approvals.',
      'Strong institutional EPC track record with metro rail, defense, and highway projects.'
    ],
    disadvantages: [
      'Residential installer footprint is primarily concentrated in Northern and Central India.',
      'Slower digital quoting process; typically requires an offline engineer survey before price confirmation.'
    ],
    productWarrantyYears: 12,
    performanceWarrantyYears: 25,
    installationAvailability: 'Nationwide',
    statesServed: ['All India'],
    tier: 'Tier-1',
    pricePerKWMin: 55000,
    pricePerKWMax: 63000,
    priceDisplay: '₹55,000 – ₹63,000 / kW',
    priceType: 'turnkey',
    inverterPartners: ['Jakson Hybrid Inverters', 'Delta', 'ABB'],
    amcAvailable: true,
    financingAvailable: true,
    subsidySupport: true,
    netMeteringSupport: true,
    evaluation: {
      overallScore: 8.6,
      priceValue: 8.4,
      productQuality: 8.8,
      warrantyScore: 8.6,
      installationScore: 8.8,
      serviceScore: 8.7,
      availabilityScore: 8.8,
      technologyScore: 8.5,
      assessmentDisclaimer: '75-year legacy engineering conglomerate offering end-to-end solar EPC and robust battery energy storage integration.',
    },
    bestFor: 'Turnkey Engineering & Hybrid Storage Solutions',
    source: 'Jakson Solar Product Matrix',
    lastVerified: 'March 2026',
    featured: false,
  },
  {
    name: 'Goldi Solar',
    slug: 'goldi-solar',
    type: 'Both',
    officialWebsite: 'https://www.goldisolar.com',
    quoteUrl: 'https://www.goldisolar.com/get-a-quote',
    headquarters: 'Surat, Gujarat',
    establishedYear: 2011,
    products: ['Heloc Plus High-Efficiency Modules', 'Veda Mono PERC', 'EPC Solutions'],
    panelTechnology: ['TOPCon', 'Mono PERC', 'Bifacial'],
    cellTechnology: 'Heloc Plus M10 / G12 Half-Cut',
    efficiencyPercent: 22.2,
    annualDegradation: '0.45% / yr linear',
    advantages: [
      'Highly automated 3+ GW manufacturing facility in Gujarat with export pedigree across 20+ countries.',
      'Very competitive turnkey pricing with excellent value per watt for residential systems.',
      'Prompt supply chain and service coverage throughout Western, Central, and Northern India.',
      'ALMM listed with full PM Surya Ghar DCR domestic compliance.'
    ],
    disadvantages: [
      'Relatively smaller brand presence in Southern and North-Eastern states.',
      'After-sales support in remote districts relies on local third-party solar integrators.'
    ],
    productWarrantyYears: 12,
    performanceWarrantyYears: 30,
    installationAvailability: 'Nationwide',
    statesServed: ['All India'],
    tier: 'Tier-1',
    pricePerKWMin: 50000,
    pricePerKWMax: 56000,
    priceDisplay: '₹50,000 – ₹56,000 / kW',
    priceType: 'turnkey',
    inverterPartners: ['Sungrow', 'GoodWe', 'Solis'],
    amcAvailable: true,
    financingAvailable: true,
    subsidySupport: true,
    netMeteringSupport: true,
    evaluation: {
      overallScore: 8.8,
      priceValue: 9.3,
      productQuality: 8.9,
      warrantyScore: 9.2,
      installationScore: 8.6,
      serviceScore: 8.5,
      availabilityScore: 8.9,
      technologyScore: 8.9,
      assessmentDisclaimer: 'Surat-based Tier-1 module manufacturer with high automated cell line and 30-year performance warranties.',
    },
    bestFor: 'Cost-Conscious Homeowners & Fast Western India Delivery',
    source: 'Goldi Solar Official Product Datasheets',
    lastVerified: 'March 2026',
    featured: false,
  },
  {
    name: 'Servotech Power Systems',
    slug: 'servotech-power-systems',
    type: 'Both',
    officialWebsite: 'https://www.servotech.in',
    quoteUrl: 'https://www.servotech.in/solar-products',
    headquarters: 'New Delhi',
    establishedYear: 2004,
    products: ['Solar Inverters', 'Mono PERC Panels', 'Lithium Storage', 'EV Fast Chargers'],
    panelTechnology: ['Mono PERC', 'Bifacial'],
    cellTechnology: 'Mono PERC Multi-Busbar',
    efficiencyPercent: 21.4,
    annualDegradation: '0.55% / yr linear',
    advantages: [
      'Complete home ecosystem: solar panels + inverters + lithium batteries + EV chargers under one brand.',
      'Strongest presence and direct maintenance support in Delhi-NCR, UP, Punjab, and Haryana.',
      'Aggressive pricing and easy EMI financing tie-ups with leading Indian banks.',
      'Integrated net-metering liaison with northern discoms (BRPL, BYPL, TPDDL, UPPCL).'
    ],
    disadvantages: [
      'Shorter product warranty (10 years) compared to 12 years offered by Tata, Waaree, and Vikram.',
      'Module manufacturing capacity is smaller than pure-play giants like Waaree or Adani.',
      'Limited EPC operations in South India.'
    ],
    productWarrantyYears: 10,
    performanceWarrantyYears: 25,
    installationAvailability: 'Nationwide',
    statesServed: ['All India'],
    tier: 'Value',
    pricePerKWMin: 49000,
    pricePerKWMax: 55000,
    priceDisplay: '₹49,000 – ₹55,000 / kW',
    priceType: 'turnkey',
    inverterPartners: ['Servotech In-House Inverters'],
    amcAvailable: true,
    financingAvailable: true,
    subsidySupport: true,
    netMeteringSupport: true,
    evaluation: {
      overallScore: 8.5,
      priceValue: 9.2,
      productQuality: 8.4,
      warrantyScore: 8.3,
      installationScore: 8.7,
      serviceScore: 8.6,
      availabilityScore: 8.9,
      technologyScore: 8.4,
      assessmentDisclaimer: 'NSE-listed power electronics and solar manufacturer with integrated EV charger and inverter capabilities.',
    },
    bestFor: 'Integrated Solar + Inverter + EV Charging Setups',
    source: 'Servotech Investor Reports & Product Catalogs',
    lastVerified: 'March 2026',
    featured: false,
  },
  {
    name: 'RenewSys India',
    slug: 'renewsys-india',
    type: 'Manufacturer',
    officialWebsite: 'https://www.renewsysworld.com',
    quoteUrl: 'https://www.renewsysworld.com/contact',
    headquarters: 'Mumbai, Maharashtra',
    establishedYear: 2011,
    products: ['DESERV Mono PERC Modules', 'CONSERV EVA Encapsulants', 'PRESERV Backsheets'],
    panelTechnology: ['Mono PERC', 'Bifacial'],
    cellTechnology: 'DESERV Mono PERC & Bifacial',
    efficiencyPercent: 21.7,
    annualDegradation: '0.50% / yr linear',
    advantages: [
      'Only 100% integrated manufacturer of cells, modules, EVA encapsulants, and backsheets in India.',
      'Exceptional bill-of-materials (BOM) quality control and PID-resistant module chemistry.',
      'Ideal choice for industrial rooftops exposed to corrosive chemicals, humidity, or dust.',
      'Global shipments to Europe, USA, and Middle East with rigorous reliability certifications.'
    ],
    disadvantages: [
      'Pure equipment manufacturer; does not provide direct residential retail installations.',
      'Homeowners must obtain quotes through independent third-party EPC developers.',
      'No direct consumer subsidy processing or net-metering handling.'
    ],
    productWarrantyYears: 10,
    performanceWarrantyYears: 25,
    installationAvailability: 'Regional',
    statesServed: ['Maharashtra', 'Gujarat', 'Karnataka', 'Tamil Nadu', 'Delhi', 'Rajasthan', 'All India'],
    tier: 'Tier-1',
    pricePerKWMin: 48000,
    pricePerKWMax: 54000,
    priceDisplay: '₹48,000 – ₹54,000 / kW (Equipment-indicative)',
    priceType: 'market_indicative',
    inverterPartners: ['Authorized Regional EPC Partners'],
    amcAvailable: false,
    financingAvailable: false,
    subsidySupport: false,
    netMeteringSupport: false,
    evaluation: {
      overallScore: 8.5,
      priceValue: 8.6,
      productQuality: 9.2,
      warrantyScore: 8.6,
      installationScore: 8.0,
      serviceScore: 8.1,
      availabilityScore: 8.4,
      technologyScore: 8.9,
      assessmentDisclaimer: 'First integrated manufacturer of Solar PV Modules and key components (EVA, Backsheets). Turnkey installations through authorized EPCs.',
    },
    bestFor: 'Industrial Rooftops & Component Quality',
    source: 'RenewSys Corporate Specifications',
    lastVerified: 'March 2026',
    featured: false,
  },
];

async function seedCompanies() {
  try {
    const conn = await mongoose.connect(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/solarsense_ai');
    console.log(`[Seed Companies] Connected to DB: ${conn.connection.host}`);

    await SolarCompany.deleteMany({});
    await CompanyPriceSnapshot.deleteMany({});

    console.log(`[Seed Companies] Seeding ${companiesData.length} verified Indian Solar Companies with Advantages & Disadvantages...`);
    for (const comp of companiesData) {
      const created = await SolarCompany.create(comp);

      // Create realistic verified price snapshots if turnkey pricing is available
      if (created.pricePerKWMin && created.pricePerKWMax) {
        const sizes = [2, 3, 5, 10];
        for (const sz of sizes) {
          await CompanyPriceSnapshot.create({
            companyId: created._id,
            systemSizeKW: sz,
            priceMin: created.pricePerKWMin * sz,
            priceMax: created.pricePerKWMax * sz,
            location: 'India (Average)',
            priceType: created.priceType,
            source: created.source,
            sourceUrl: created.officialWebsite,
            capturedAt: new Date(),
          });
        }
      }
      console.log(` -> Added ${created.name} (${created.type}) with ${created.advantages.length} Pros & ${created.disadvantages.length} Cons`);
    }

    console.log('[Seed Companies] Completed successfully!');
    process.exit(0);
  } catch (err) {
    console.error('[Seed Companies Error]', err);
    process.exit(1);
  }
}

seedCompanies();
