import React, { useState, useEffect } from 'react';
import { FileText } from 'lucide-react';
import { adminService } from '../../services/adminService';
import LoadingSpinner from '../../components/common/LoadingSpinner';
import { formatCurrency, formatKW } from '../../utils/formatters';

const AdminReportsPage = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const res = await adminService.getReports();
        if (res.success) {
          setReports(res.reports);
        }
      } catch (err) {
        console.error('Error fetching admin reports:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchReports();
  }, []);

  if (loading) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <LoadingSpinner text="Retrieving platform reports registry..." />
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto space-y-5">
      <div>
        <h2 className="text-2xl sm:text-3xl font-bold text-light-text tracking-tight">
          Platform Solar Reports Registry ({reports.length})
        </h2>
        <p className="text-helper text-light-muted dark:text-dark-muted mt-0.5">
          Audit trail of all feasibility documents generated by consumers across the platform.
        </p>
      </div>

      <div className="lc-card overflow-hidden">
        {reports.length === 0 ? (
          <div className="text-center py-16 px-4 flex flex-col items-center justify-center">
            <div className="w-12 h-12 rounded-full bg-light-surface flex items-center justify-center text-light-muted mb-3 border border-light-border">
              <FileText className="w-6 h-6 text-light-muted" />
            </div>
            <p className="text-[16px] font-semibold text-light-text">No reports generated on the platform yet</p>
            <p className="text-[14px] text-light-muted max-w-sm mt-1">
              Audit reports will appear here once consumers perform sizing evaluations.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-body border-collapse">
              <thead>
                <tr className="border-b border-light-border dark:border-dark-border bg-light-surface dark:bg-dark-surface text-label uppercase font-semibold text-light-muted dark:text-dark-muted tracking-wider">
                  <th className="py-3 px-4">Report Number</th>
                  <th className="py-3 px-3">Consumer Name</th>
                  <th className="py-3 px-3">Category</th>
                  <th className="py-3 px-3">Recommended Sizing</th>
                  <th className="py-3 px-3">Net Outlay</th>
                  <th className="py-3 px-3">Annual Savings</th>
                  <th className="py-3 px-4 text-right">Generated At</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-light-border dark:divide-dark-border text-light-text dark:text-dark-text">
                {reports.map((r) => (
                  <tr key={r._id} className="hover:bg-light-surface/60 dark:hover:bg-dark-surface/60 transition-colors">
                    <td className="py-3.5 px-4 font-mono font-semibold text-brand-green">
                      {r.reportNumber}
                    </td>
                    <td className="py-3.5 px-3 font-semibold">
                      {r.summaryData?.userName || r.userId?.name || 'Consumer'}
                    </td>
                    <td className="py-3.5 px-3 capitalize">
                      <span className="px-2 py-0.5 rounded-btn text-label font-medium lc-surface border border-light-border dark:border-dark-border">
                        {r.summaryData?.userType?.replace('_', ' ') || 'Residential'}
                      </span>
                    </td>
                    <td className="py-3.5 px-3 font-semibold">
                      {formatKW(r.summaryData?.outputs?.recommendedCapacity || 0)}
                    </td>
                    <td className="py-3.5 px-3 text-light-muted dark:text-dark-muted">
                      {formatCurrency(r.summaryData?.outputs?.netCost || 0)}
                    </td>
                    <td className="py-3.5 px-3 text-brand-green font-semibold">
                      {formatCurrency(r.summaryData?.outputs?.annualSavings || 0)}/yr
                    </td>
                    <td className="py-3.5 px-4 text-right text-light-muted dark:text-dark-muted text-label">
                      {new Date(r.generatedAt).toLocaleDateString('en-IN')}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminReportsPage;
